# Generated by Django 3.2.12 on 2022-05-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20220520_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='recommend_movies',
            field=models.ManyToManyField(related_name='recommended', to='movies.Movie'),
        ),
    ]
