# Generated by Django 3.2.12 on 2022-05-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='food_taste',
            field=models.ManyToManyField(related_name='food_taste', to='communities.Taste'),
        ),
    ]
