# Generated by Django 3.2.12 on 2022-05-24 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20220520_1655'),
        ('communities', '0003_rename_food_taste_food_taste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('taste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.taste')),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_blacklist',
        ),
        migrations.DeleteModel(
            name='BlackList',
        ),
        migrations.AddField(
            model_name='taste',
            name='tastee_algo',
            field=models.ManyToManyField(through='communities.Algo', to='movies.Genre'),
        ),
    ]
