# Generated by Django 3.2.12 on 2022-05-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20220524_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taste',
            old_name='tastee_algo',
            new_name='taste_algo',
        ),
    ]
